### ISSUE TITLE
Generating cache access methods for graphql client

### ISSUE THREAD

**Issue by jhlabs** [heftapp/graphql_codegen#54]
I love using this library with the `graphql` package for safe type access.

When accessing and writing to the cache though I am largely left to working with untyped maps again. It would be great to generate the `readQuery`, `writeQuery`, `readFragment` and `writeFragment` with this package!

I would be happy to help on a PR if @budde377 also thinks this would be a valuable addition?

**Comment by budde377** [comment]
I love this idea! I think we'll need to:

**Make the generated `Fragment` abstract classes concrete and serializable:** 

Right now, the fragments are used as interfaces, but for us to be able to write (and read) fragments we'll need to be able to instantiate them. This shouldn't be too complicated, but some complexity might arise from making the classes extend `JsonSerializable` and generated helper methods.

**Extend the client with fragment methods**

My intuition tells me that we should extend the GraphQL Client with appropriate methods, e.g. for `writeFragment`:

```graphql
fragment PersonFragment {
  name
  age
}
```

```dart
void writeFragment({
  bool broadcast = true,
  required FragmentPersonFragment data,
  required IDFieldsFragmentPersonFragment idFields,
  required VariablesFragmentPersonFragment variables, // Required depending on the variables
})
```

For the id fields, we can add a configuration allowing users to specify which fields are id fields (default to `__typename` and `id`). Then we can inspect the fragment to see if it contains these fields. Any field contained in the fragment will be removed from the `IDFields*` class. If there are no fields left, we can omit the idFields argument.

For the variables, we'll have to infer this by going through all fields in this fragment and referenced fragments.

**Extend the client with query methods** 

For this we should already have appropriate serializers for variables and the data.


Am I missing anything @jhlabs?

**Comment by jhlabs** [comment]
That looks right to me! 

The `IDFields` is a tricky one. The `GraphQLClient` allows them to be specified for each type individually through a `TypePolicy` that comes from the `normalize` package. Where you thinking to be able to add a configuration for each type as well?

**Comment by budde377** [comment]
You're right. The problem with a configuration on the types is that a fragment might be on an interface, which means that we'll need to take into account all combinations of ID-fileds for all "concrete" types. 

I think, for the first version, we can just make the ID fields a `Map<String, dynamic>`.

**Comment by jhlabs** [comment]
This is great @budde377! Thanks for implementing that.

When I have fragments that nest other fragments the generated code has a compile error in the functions for nested read and write cache methods. An example below (The Fragment `Block` has a nested fragment `BlockReaction`):
```dart
extension ClientExtensionFragmentBlock$blockReactions on graphql.GraphQLClient {
  void writeFragmentBlock$blockReactions(
          {required FragmentBlock$blockReactions data,
          required Map<String, dynamic> idFields,
          Map<String, dynamic> variables = const {},
          broadcast = true}) =>
      this.writeFragment(
          graphql.FragmentRequest(
              idFields: idFields,
              fragment: graphql.Fragment(
                  document: const DocumentNode(
                      definitions: [FRAGMENT_BLOCK$BLOCK_REACTIONS])),
              variables: variables),
          data: data.toJson(),
          broadcast: broadcast);
  FragmentBlock$blockReactions? readFragmentBlock$blockReactions(
      {required Map<String, dynamic> idFields,
      Map<String, dynamic> variables = const {},
      optimistic = true}) {
    final result = this.readFragment(
        graphql.FragmentRequest(
            idFields: idFields,
            fragment: graphql.Fragment(
                document: const DocumentNode(
                    definitions: [FRAGMENT_BLOCK$BLOCK_REACTIONS])),
            variables: variables),
        optimistic: optimistic);
    return result == null
        ? null
        : FragmentBlock$blockReactions.fromJson(result);
  }
}
```

`FRAGMENT_BLOCK$BLOCK_REACTIONS` cannot be found. If I replace this replace this variable with the definition node `FRAGMENT_BLOCK_REACTION`  from the related nested fragment it shows no errors (I haven't tried whether the methods actually work though).

So I think either the node `FRAGMENT_BLOCK$BLOCK_REACTIONS` would need to be generated as part of the current file or in the nested read and writes we would reference `FRAGMENT_BLOCK_REACTION`.

I am including the entire generated as well as the original graphql files for the two fragments below for reference:

**block.graphql**
```graphql
# import './block_reaction.graphql'

fragment Block on blocks {
  id
  title
  type
  attributes
  creator
  block_reactions {
    ...BlockReaction
  }
}
```

**block_reaction.graphql**
```graphql
fragment BlockReaction on block_reactions {
  count
  block_id
  profile_id
  reaction_name
}
```

**block.graphql.dart**
```dart
// ignore_for_file: constant_identifier_names, unnecessary_const, non_constant_identifier_names
// ignore_for_file: unnecessary_this, annotate_overrides, prefer_is_not_operator, curly_braces_in_flow_control_structures

import 'block_reaction.graphql.dart';
import 'package:gql/ast.dart';
import 'package:graphql/client.dart' as graphql;
import 'package:json_annotation/json_annotation.dart';
part 'block.graphql.g.dart';

@JsonSerializable()
class FragmentBlock extends JsonSerializable {
  FragmentBlock(
      {required this.id,
      this.title,
      required this.type,
      required this.attributes,
      required this.creator,
      required this.block_reactions,
      required this.$__typename});

  @override
  factory FragmentBlock.fromJson(Map<String, dynamic> json) =>
      _$FragmentBlockFromJson(json);

  final String id;

  final String? title;

  final String type;

  final Map<String, dynamic> attributes;

  final String creator;

  final List<FragmentBlock$blockReactions> block_reactions;

  @JsonKey(name: '__typename')
  final String $__typename;

  @override
  Map<String, dynamic> toJson() => _$FragmentBlockToJson(this);
  int get hashCode {
    final l$id = id;
    final l$title = title;
    final l$type = type;
    final l$attributes = attributes;
    final l$creator = creator;
    final l$block_reactions = block_reactions;
    final l$$__typename = $__typename;
    return Object.hashAll([
      l$id,
      l$title,
      l$type,
      l$attributes,
      l$creator,
      Object.hashAll(l$block_reactions.map((v) => v)),
      l$$__typename
    ]);
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (!(other is FragmentBlock) || runtimeType != other.runtimeType)
      return false;
    final l$id = id;
    final lOther$id = other.id;
    if (l$id != lOther$id) return false;
    final l$title = title;
    final lOther$title = other.title;
    if (l$title != lOther$title) return false;
    final l$type = type;
    final lOther$type = other.type;
    if (l$type != lOther$type) return false;
    final l$attributes = attributes;
    final lOther$attributes = other.attributes;
    if (l$attributes != lOther$attributes) return false;
    final l$creator = creator;
    final lOther$creator = other.creator;
    if (l$creator != lOther$creator) return false;
    final l$block_reactions = block_reactions;
    final lOther$block_reactions = other.block_reactions;
    if (l$block_reactions.length != lOther$block_reactions.length) return false;
    for (int i = 0; i < l$block_reactions.length; i++) {
      final l$block_reactions$entry = l$block_reactions[i];
      final lOther$block_reactions$entry = lOther$block_reactions[i];
      if (l$block_reactions$entry != lOther$block_reactions$entry) return false;
    }

    final l$$__typename = $__typename;
    final lOther$$__typename = other.$__typename;
    if (l$$__typename != lOther$$__typename) return false;
    return true;
  }
}

const FRAGMENT_BLOCK = const FragmentDefinitionNode(
    name: NameNode(value: 'Block'),
    typeCondition: TypeConditionNode(
        on: NamedTypeNode(name: NameNode(value: 'blocks'), isNonNull: false)),
    directives: [],
    selectionSet: SelectionSetNode(selections: [
      FieldNode(
          name: NameNode(value: 'id'),
          alias: null,
          arguments: [],
          directives: [],
          selectionSet: null),
      FieldNode(
          name: NameNode(value: 'title'),
          alias: null,
          arguments: [],
          directives: [],
          selectionSet: null),
      FieldNode(
          name: NameNode(value: 'type'),
          alias: null,
          arguments: [],
          directives: [],
          selectionSet: null),
      FieldNode(
          name: NameNode(value: 'attributes'),
          alias: null,
          arguments: [],
          directives: [],
          selectionSet: null),
      FieldNode(
          name: NameNode(value: 'creator'),
          alias: null,
          arguments: [],
          directives: [],
          selectionSet: null),
      FieldNode(
          name: NameNode(value: 'block_reactions'),
          alias: null,
          arguments: [],
          directives: [],
          selectionSet: SelectionSetNode(selections: [
            FragmentSpreadNode(
                name: NameNode(value: 'BlockReaction'), directives: []),
            FieldNode(
                name: NameNode(value: '__typename'),
                alias: null,
                arguments: [],
                directives: [],
                selectionSet: null)
          ])),
      FieldNode(
          name: NameNode(value: '__typename'),
          alias: null,
          arguments: [],
          directives: [],
          selectionSet: null)
    ]));

extension ClientExtensionFragmentBlock on graphql.GraphQLClient {
  void writeFragmentBlock(
          {required FragmentBlock data,
          required Map<String, dynamic> idFields,
          Map<String, dynamic> variables = const {},
          broadcast = true}) =>
      this.writeFragment(
          graphql.FragmentRequest(
              idFields: idFields,
              fragment: graphql.Fragment(
                  document: const DocumentNode(definitions: [FRAGMENT_BLOCK])),
              variables: variables),
          data: data.toJson(),
          broadcast: broadcast);
  FragmentBlock? readFragmentBlock(
      {required Map<String, dynamic> idFields,
      Map<String, dynamic> variables = const {},
      optimistic = true}) {
    final result = this.readFragment(
        graphql.FragmentRequest(
            idFields: idFields,
            fragment: graphql.Fragment(
                document: const DocumentNode(definitions: [FRAGMENT_BLOCK])),
            variables: variables),
        optimistic: optimistic);
    return result == null ? null : FragmentBlock.fromJson(result);
  }
}

@JsonSerializable()
class FragmentBlock$blockReactions extends JsonSerializable
    implements FragmentBlockReaction {
  FragmentBlock$blockReactions(
      {required this.count,
      required this.block_id,
      required this.profile_id,
      required this.reaction_name,
      required this.$__typename});

  @override
  factory FragmentBlock$blockReactions.fromJson(Map<String, dynamic> json) =>
      _$FragmentBlock$blockReactionsFromJson(json);

  final int count;

  final String block_id;

  final String profile_id;

  final String reaction_name;

  @JsonKey(name: '__typename')
  final String $__typename;

  @override
  Map<String, dynamic> toJson() => _$FragmentBlock$blockReactionsToJson(this);
  int get hashCode {
    final l$count = count;
    final l$block_id = block_id;
    final l$profile_id = profile_id;
    final l$reaction_name = reaction_name;
    final l$$__typename = $__typename;
    return Object.hashAll(
        [l$count, l$block_id, l$profile_id, l$reaction_name, l$$__typename]);
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (!(other is FragmentBlock$blockReactions) ||
        runtimeType != other.runtimeType) return false;
    final l$count = count;
    final lOther$count = other.count;
    if (l$count != lOther$count) return false;
    final l$block_id = block_id;
    final lOther$block_id = other.block_id;
    if (l$block_id != lOther$block_id) return false;
    final l$profile_id = profile_id;
    final lOther$profile_id = other.profile_id;
    if (l$profile_id != lOther$profile_id) return false;
    final l$reaction_name = reaction_name;
    final lOther$reaction_name = other.reaction_name;
    if (l$reaction_name != lOther$reaction_name) return false;
    final l$$__typename = $__typename;
    final lOther$$__typename = other.$__typename;
    if (l$$__typename != lOther$$__typename) return false;
    return true;
  }
}

extension ClientExtensionFragmentBlock$blockReactions on graphql.GraphQLClient {
  void writeFragmentBlock$blockReactions(
          {required FragmentBlock$blockReactions data,
          required Map<String, dynamic> idFields,
          Map<String, dynamic> variables = const {},
          broadcast = true}) =>
      this.writeFragment(
          graphql.FragmentRequest(
              idFields: idFields,
              fragment: graphql.Fragment(
                  document: const DocumentNode(
                      definitions: [FRAGMENT_BLOCK$BLOCK_REACTIONS])),
              variables: variables),
          data: data.toJson(),
          broadcast: broadcast);
  FragmentBlock$blockReactions? readFragmentBlock$blockReactions(
      {required Map<String, dynamic> idFields,
      Map<String, dynamic> variables = const {},
      optimistic = true}) {
    final result = this.readFragment(
        graphql.FragmentRequest(
            idFields: idFields,
            fragment: graphql.Fragment(
                document: const DocumentNode(
                    definitions: [FRAGMENT_BLOCK$BLOCK_REACTIONS])),
            variables: variables),
        optimistic: optimistic);
    return result == null
        ? null
        : FragmentBlock$blockReactions.fromJson(result);
  }
}
```

**block_reaction.graphql.dart**
```dart
// ignore_for_file: constant_identifier_names, unnecessary_const, non_constant_identifier_names
// ignore_for_file: unnecessary_this, annotate_overrides, prefer_is_not_operator, curly_braces_in_flow_control_structures

import 'package:gql/ast.dart';
import 'package:graphql/client.dart' as graphql;
import 'package:json_annotation/json_annotation.dart';
part 'block_reaction.graphql.g.dart';

@JsonSerializable()
class FragmentBlockReaction extends JsonSerializable {
  FragmentBlockReaction(
      {required this.count,
      required this.block_id,
      required this.profile_id,
      required this.reaction_name,
      required this.$__typename});

  @override
  factory FragmentBlockReaction.fromJson(Map<String, dynamic> json) =>
      _$FragmentBlockReactionFromJson(json);

  final int count;

  final String block_id;

  final String profile_id;

  final String reaction_name;

  @JsonKey(name: '__typename')
  final String $__typename;

  @override
  Map<String, dynamic> toJson() => _$FragmentBlockReactionToJson(this);
  int get hashCode {
    final l$count = count;
    final l$block_id = block_id;
    final l$profile_id = profile_id;
    final l$reaction_name = reaction_name;
    final l$$__typename = $__typename;
    return Object.hashAll(
        [l$count, l$block_id, l$profile_id, l$reaction_name, l$$__typename]);
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (!(other is FragmentBlockReaction) || runtimeType != other.runtimeType)
      return false;
    final l$count = count;
    final lOther$count = other.count;
    if (l$count != lOther$count) return false;
    final l$block_id = block_id;
    final lOther$block_id = other.block_id;
    if (l$block_id != lOther$block_id) return false;
    final l$profile_id = profile_id;
    final lOther$profile_id = other.profile_id;
    if (l$profile_id != lOther$profile_id) return false;
    final l$reaction_name = reaction_name;
    final lOther$reaction_name = other.reaction_name;
    if (l$reaction_name != lOther$reaction_name) return false;
    final l$$__typename = $__typename;
    final lOther$$__typename = other.$__typename;
    if (l$$__typename != lOther$$__typename) return false;
    return true;
  }
}

const FRAGMENT_BLOCK_REACTION = const FragmentDefinitionNode(
    name: NameNode(value: 'BlockReaction'),
    typeCondition: TypeConditionNode(
        on: NamedTypeNode(
            name: NameNode(value: 'block_reactions'), isNonNull: false)),
    directives: [],
    selectionSet: SelectionSetNode(selections: [
      FieldNode(
          name: NameNode(value: 'count'),
          alias: null,
          arguments: [],
          directives: [],
          selectionSet: null),
      FieldNode(
          name: NameNode(value: 'block_id'),
          alias: null,
          arguments: [],
          directives: [],
          selectionSet: null),
      FieldNode(
          name: NameNode(value: 'profile_id'),
          alias: null,
          arguments: [],
          directives: [],
          selectionSet: null),
      FieldNode(
          name: NameNode(value: 'reaction_name'),
          alias: null,
          arguments: [],
          directives: [],
          selectionSet: null),
      FieldNode(
          name: NameNode(value: '__typename'),
          alias: null,
          arguments: [],
          directives: [],
          selectionSet: null)
    ]));

extension ClientExtensionFragmentBlockReaction on graphql.GraphQLClient {
  void writeFragmentBlockReaction(
          {required FragmentBlockReaction data,
          required Map<String, dynamic> idFields,
          Map<String, dynamic> variables = const {},
          broadcast = true}) =>
      this.writeFragment(
          graphql.FragmentRequest(
              idFields: idFields,
              fragment: graphql.Fragment(
                  document: const DocumentNode(
                      definitions: [FRAGMENT_BLOCK_REACTION])),
              variables: variables),
          data: data.toJson(),
          broadcast: broadcast);
  FragmentBlockReaction? readFragmentBlockReaction(
      {required Map<String, dynamic> idFields,
      Map<String, dynamic> variables = const {},
      optimistic = true}) {
    final result = this.readFragment(
        graphql.FragmentRequest(
            idFields: idFields,
            fragment: graphql.Fragment(
                document:
                    const DocumentNode(definitions: [FRAGMENT_BLOCK_REACTION])),
            variables: variables),
        optimistic: optimistic);
    return result == null ? null : FragmentBlockReaction.fromJson(result);
  }
}
```

**Comment by budde377** [comment]
Thanks for reporting back! We're generating too many cache methods. I think it's reasonable to expect that for each fragment we'll generate exactly one write and one read method.

The fix should be out in [0.7.0-beta.9](https://pub.dev/packages/graphql_codegen/versions/0.7.0-beta.9)

**Comment by jhlabs** [comment]
This works perfectly!

I have one issue with reading a fragment with nested fragments. It might not be related to this library, but I thought I mention it and can raise it otherwise in the `graphql` repo.

When I query for a fragment in a cache that includes nested fragments (in this case as a list), the `readFragment` method throws an exception.

For example, I run the following cache query:

```dart
 final blockIdFields = {
      '__typename': 'blocks',
      'id': blockId,
};
final block = _client.readFragmentBlock(idFields: blockIdFields);
```

I get the following exception:

```
flutter: ══╡ EXCEPTION CAUGHT BY ╞═══════════════════════════════════════════════════════════════════════════
flutter: The following _Exception was thrown Exception: Missing fragment BlockReaction:
flutter: Exception: Missing fragment BlockReaction
```

The `BlockReaction` fragment is nested under the `Block` fragment. If the `Block` fragment does not contain any child fragments, i.e. the list is empty, the query passes fine.

Any clue on why that error might occur?

**Comment by budde377** [comment]
The problem is that we were not adding the `FragmentDefnitionNode`s of the nested fragments. This should be fixed in `0.7.0-beta.10`.

**Comment by jhlabs** [comment]
`0.7.0-beta.10` solved it perfectly!

I am now facing a final issue at a, what I believe, typical scenario for cache updates. I have the `Block` that holds a list of `BlockReactions` and now I want to add a new `BlockReaction` to it. Below you see how I am currently trying to update the cache:

```dart
    // This works without any issues now.
    final block = _client.readFragmentBlock(idFields: blockIdFields);

    if (block == null) {
      _log.severe(
          'Could not update block with id $blockId because it could not be found.');
      return;
    }
    
    // The only reason I am converting this list is to make easy immutable updates to it.
    final reactionList = block.block_reactions.toIList();

    // Here I would have expected that `FragmentBlockReaction` can be passed as well.
    final newReaction = FragmentBlock$blockReactions(
      count: 1,
      block_id: blockId,
      profile_id: profileId,
      reaction_name: reactionName,
      $__typename: 'block_reactions',
    );
    
    // This is an immutable method to create a new list with the new item added last
    final newList = reactionList.add(newReaction);

    final newBlock = FragmentBlock(
      id: block.id,
      title: block.title,
      type: block.type,
      attributes: block.attributes,
      creator: block.creator,
      block_reactions: newList.toList(),
      $__typename: block.$__typename,
    );
   
    // This write method fails with below error message
    _client.writeFragmentBlock(
      data: newBlock,
      idFields: blockIdFields,
    );
```

Two thoughts I had that might be out of scope for this ticket or library, but thought worth mentioning:
1. I expected to be able to pass the nested fragment `FragmentBlockReaction` directly into the list. This is one of the big strength of `graphql_codegen` that it accepts the original fragment usually in nested queries, etc. Here however, it seems to only allow for the type listed in the original `BlockReaction`.
2. The act of reading a block from the cache, modifying it immutably and then writing it back to the cache is probably so common that it might be worth to introduce a `copyWith` extension on the fragment. Maybe I also just didn't use an already available more straightforward way to do this.

The main issue I have is that the `writeFragment` call fails with the following error:

```
flutter: The following _Exception was thrown Exception: There are sub-selections on this node, but the data
flutter: is not null, an Array, or a Map:
flutter: Exception: There are sub-selections on this node, but the data is not null, an Array, or a Map
```

I assume that the subnodes of `BlockReaction` might not be converted back to a map before being handled by the `normalize` library? Am I even supposed to use the cache methods like these or should I somehow make two different cache writes?

Thanks for your help.

**Comment by budde377** [comment]
Thanks for getting back again with such thorough feedback.

> I expected to be able to pass the nested fragment FragmentBlockReaction directly into the list. This is one of the big strength of graphql_codegen that it accepts the original fragment usually in nested queries, etc. Here however, it seems to only allow for the type listed in the original BlockReaction.

I see where you're coming from here. The problem is that we can't generally assume that the nested fragment contains all the fields. Take this query:

```graphql
fragment Block on blocks {
  id
  title
  type
  attributes
  creator
  block_reactions {
    someExtraField
    ...BlockReaction
  }
}
```

In this case passing the `FragmentBlockReaction` will be missing the `someExtraField`.

> The act of reading a block from the cache, modifying it immutable, and then writing it back to the cache is probably so common that it might be worth to introduce a copyWith extension on the fragment. Maybe I also just didn't use an already available more straightforward way to do this.

This makes a lot of sense. I've now added this.

> The main issue I have is that the writeFragment call fails with the following error:

This was because we're not explicitly calling `toJson` on the nested serializer classes. This should now be fixed.

Please try `0.7.0-beta.11` with the fixes and changes! And again, thank you for your feedback.

**Comment by jhlabs** [comment]
This is great, I just deleted a lot of untyped code with these changes!

> In this case passing the `FragmentBlockReaction` will be missing the `someExtraField`.

Yes, you are totally right. We cannot make that assumption.

There are only two minor questions left that I noticed while replacing all my cache related code:

It seems that optional fields are generated as a function instead of just the optional value. For example, the following utility addition for the `FragmentBlock` requires you to pass an optional function instead of the `String` directly. Is that intended?

```graphql

```

```dart
@JsonSerializable(explicitToJson: true)
class FragmentBlock extends JsonSerializable {
  FragmentBlock(
      {required this.id,
      this.title,
      required this.type,
      required this.attributes,
      required this.creator,
      required this.block_reactions,
      required this.$__typename});

  @override
  factory FragmentBlock.fromJson(Map<String, dynamic> json) =>
      _$FragmentBlockFromJson(json);

  final String id;

  final String? title;

  final String type;

  final Map<String, dynamic> attributes;

  final String creator;

  final List<FragmentBlock$blockReactions> block_reactions;

  @JsonKey(name: '__typename')
  final String $__typename;

  @override
  Map<String, dynamic> toJson() => _$FragmentBlockToJson(this);
  int get hashCode {
    final l$id = id;
    final l$title = title;
    final l$type = type;
    final l$attributes = attributes;
    final l$creator = creator;
    final l$block_reactions = block_reactions;
    final l$$__typename = $__typename;
    return Object.hashAll([
      l$id,
      l$title,
      l$type,
      l$attributes,
      l$creator,
      Object.hashAll(l$block_reactions.map((v) => v)),
      l$$__typename
    ]);
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (!(other is FragmentBlock) || runtimeType != other.runtimeType)
      return false;
    final l$id = id;
    final lOther$id = other.id;
    if (l$id != lOther$id) return false;
    final l$title = title;
    final lOther$title = other.title;
    if (l$title != lOther$title) return false;
    final l$type = type;
    final lOther$type = other.type;
    if (l$type != lOther$type) return false;
    final l$attributes = attributes;
    final lOther$attributes = other.attributes;
    if (l$attributes != lOther$attributes) return false;
    final l$creator = creator;
    final lOther$creator = other.creator;
    if (l$creator != lOther$creator) return false;
    final l$block_reactions = block_reactions;
    final lOther$block_reactions = other.block_reactions;
    if (l$block_reactions.length != lOther$block_reactions.length) return false;
    for (int i = 0; i < l$block_reactions.length; i++) {
      final l$block_reactions$entry = l$block_reactions[i];
      final lOther$block_reactions$entry = lOther$block_reactions[i];
      if (l$block_reactions$entry != lOther$block_reactions$entry) return false;
    }

    final l$$__typename = $__typename;
    final lOther$$__typename = other.$__typename;
    if (l$$__typename != lOther$$__typename) return false;
    return true;
  }
}


extension UtilityExtensionFragmentBlock on FragmentBlock {
  FragmentBlock copyWith(
          {String? id,
         // Here we are required to pass a function
          String? Function()? title,
          String? type,
          Map<String, dynamic>? attributes,
          String? creator,
          List<FragmentBlock$blockReactions>? block_reactions,
          String? $__typename}) =>
      FragmentBlock(
          id: id == null ? this.id : id,
          title: title == null ? this.title : title(),
          type: type == null ? this.type : type,
          attributes: attributes == null ? this.attributes : attributes,
          creator: creator == null ? this.creator : creator,
          block_reactions:
              block_reactions == null ? this.block_reactions : block_reactions,
          $__typename: $__typename == null ? this.$__typename : $__typename);
}
```

The second question is related to updating optional fields in the cache. I have a field called `title` that is optional and can thereby be null. However, when I try to update the cache with the typed classes provided by `graphql_codegen` it throws the following error:

```
flutter: The following PartialDataException was thrown PartialDataException(path: block_pages.block.title):
flutter: PartialDataException(path: block_pages.block.title)
```

Also, when I set the `title` explicitly to null it throws the error. Do you know how this issue could be solved? I am including the code I use to update the cache with this nested value below:

```dart
 final idFields = {
      '__typename': 'pages',
      'id': pageId,
    };

    final page = _client.readFragmentPage(idFields: idFields);

    if (page == null) {
      return _log.severe('Could not update cache for page with id $pageId');
    }

    final block = FragmentPage$blockPages$block(
      $__typename: 'blocks',
      attributes: attributes,
      id: blockId,
      block_reactions: [],
      creator: profileId,
      type: blockType.name,
      // Here I am setting the field to null. Ideally, I would just exclude this property since it should be null. In either case an error is thrown.
      title: null,
    );

    final blockEntry = FragmentPage$blockPages(
      $__typename: 'block_page',
      id: blockPageId,
      position: position,
      block: block,
    );

    final newBlockEntries = page.block_pages
        .toIList()
        .add(blockEntry)
        .sort((a, b) => a.position.compareTo(b.position))
        .toList();

    _client.writeFragmentPage(
      data: page.copyWith(block_pages: newBlockEntries),
      idFields: idFields,
    );

    return _log
        .info('Updated page fragment with id $pageId in cache with new block');
```

The cache additions are so helpful and I have already caught a bunch of potential bugs with the typing. Thanks again for implementing this!

**Comment by budde377** [comment]
Thanks for getting back! This is great news.

> It seems that optional fields are generated as a function instead of just the optional value

This is intended! The problem is that we can't differentiate between you passing a `null` to the copy method (e.g. `copyWith(title: null)`) or not choosing to override an argument, e.g. `copyWith()`. In JS you'd be able to express this with `undefined` and `null`, but in dart you need to do something else. 

There're different methods to overcome this issue, you can use a wrapper class which, if provided, contains the value. The problem with this method is that we'd either need to generate a utility class for each file or schema, or add a dependency. None of these are super appealing. 

Alternatively, we can use a function, which serves the same purpose and requires no additional classes.

> The second question is related to updating optional fields in the cache. I have a field called title that is optional and can thereby be null. However, when I try to update the cache with the typed classes provided by graphql_codegen it throws the following error:

This is interesting. I'd suspect that this is related to #62 where the `null` values in your setup are stripped from the serializer. I think we should add a configuration which allows us to only strip null values from input serializers (variables and input).

**Comment by budde377** [comment]
@jhlabs, please check `0.7.0-beta.12` for the new option to only strip fields containing `null` from input serializers (https://github.com/heftapp/graphql_codegen/tree/main/packages/graphql_codegen#strip-null-from-input-serializers)

**Comment by jhlabs** [comment]
@budde377 thanks for this update!

Makes perfect sense with the function. I was just unsure whether it was accidentally generating it.

I tested out the new version `0.7.0-beta.12` and it has not resolved the issue. I was actually already including the `include_if_null: false` configuration for `json_serializable` after you pointed out this issue in #46.

When I debug the `data` that is passed to the `graphql_client` library it correctly strips out the null values. Is there a requirement to define the nullable values in the `FragmentDefinitionNode` that we might be missing somewhere?

**Comment by budde377** [comment]
@jhlabs, did you add the new option [includeIfNullOnInput](https://github.com/heftapp/graphql_codegen/tree/main/packages/graphql_codegen#strip-null-from-input-serializers) and remove the `include_if_null` setting on the JSON serialisers? The new option should remove the need for the other option and solve your partial data problem.

**Comment by jhlabs** [comment]
@budde377 thanks this works perfectly now. I didn't remove the `include_if_null` before and removing it solved the issue.
